### ISSUE TITLE
config.externals is undefined in nextjs 8.1

### ISSUE THREAD

**Issue by Ktchan825** [wellcometrust/next-plugin-transpile-modules#11]
Just upgraded to next.js version 8.1
execute `npm run dev`
Error is reported as config.externals is undefined.
`(node:11843) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at Object.webpack (/Users/imsure/gavin-chan/Gitlab/imsure_web_fe/node_modules/next-plugin-transpile-modules/index.js:32:43)`

FYI: 
[https://github.com/zeit/next.js/pull/6983](https://github.com/zeit/next.js/pull/6983)

[https://github.com/zeit/next.js/issues/6946](https://github.com/zeit/next.js/issues/6946)

**Comment by EyMaddis** [comment]
Workaround (here using [withPlugins](https://github.com/cyrilwanner/next-compose-plugins)):

```js

function fixExternalsPlugin(config = {}) {
  const { webpack } = config
  config.webpack = (config, ...rest) => {
    config.externals = config.externals || []
    return webpack(config, ...rest)
  }
  return config
}

module.exports = withPlugins(
  [
    // should be the most nested according to the docs
    [
      withTM,
      {
        transpileModules: ReactNativeModules,
      },
    ],
    [fixExternalsPlugin],
    ....
])
```

This probably breaks at some point, but might work for now.
